#!/bin/sh
exec lush "$0" "$@"
!#

;; A Simple calculator
(when (or (member "-h" argv)
          (member "--help" argv))
  (writing "$stderr" 
   (render-brace-text 0 72
   '{<p> Synopsis: ,,(basename (car argv)) [-h]{<br>}
     A simple GUI calculator.
     Option "-h" shows this message. 
     }))
  (exit 0))

(libload "libogre/calctool")
(wait (new c-calctool))




