#!/bin/sh
exec lush "$0" "$@"
!#

;; OpenGL and SDL

(when (or (member "-h" argv)
          (member "--help" argv))
  (writing "$stderr" 
   (render-brace-text 0 72
   '{<p> Synopsis: ,,(basename (car argv)) [-h] [nobjects]{<br>}
     Bounces a bunch of sprites on top of a background using SDL.
     The optional argument [nobjects] specifies the number of copies
     of the sprite that will be bounced around. Default is 100.
     Option "-h" shows this message. 
     }))
  (exit 0))

(setq nobj 100)
(when (cadr argv)
  (setq nobj (or (val (cadr argv)) nobj)))

(libload "sdl/libsdl")

(writing "/dev/null" (libload "sdl/demos/libsdl-demo"))

(sdl-bouncy 
  (concat lushdir "/packages/sdl/demos/lem.png")
  (concat lushdir "/packages/sdl/demos/moon.png") 
  nobj)


