#!/bin/sh
exec lush "$0" "$@"
!#


(when (or (member "-h" argv)
          (member "--help" argv))
  (writing "$stderr" 
   (render-brace-text 0 72
   '{<p> Synopsis: ,,(basename (car argv)) [-h]{<br>}
     A simple pong-like game.
     Option "-h" shows this message. 
     }))
  (exit 0))

(chdir (concat-fname lushdir "packages/sdlgames/slimevolley"))
(libload "slime")
(slime)
